"""empty message

Revision ID: 020fc8293cf2
Revises: fd013875ee22
Create Date: 2022-04-07 17:21:45.442472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020fc8293cf2'
down_revision = 'fd013875ee22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('education', sa.Boolean(), nullable=True))
    op.add_column('resume', sa.Column('work_experience', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'work_experience')
    op.drop_column('resume', 'education')
    # ### end Alembic commands ###
