"""empty message

Revision ID: 391a60415eab
Revises: 0582d5807616
Create Date: 2022-04-06 18:16:29.345910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391a60415eab'
down_revision = '0582d5807616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('about_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skills', 'about', ['about_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_column('skills', 'about_id')
    # ### end Alembic commands ###
