"""empty message

Revision ID: 50dd9f9fcf33
Revises: 391a60415eab
Create Date: 2022-04-06 18:32:59.397386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50dd9f9fcf33'
down_revision = '391a60415eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('backend', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'backend')
    # ### end Alembic commands ###
