"""empty message

Revision ID: 5f7ddf86b9fb
Revises: a3eb3992c2e7
Create Date: 2022-04-09 19:16:01.369382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7ddf86b9fb'
down_revision = 'a3eb3992c2e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=72), nullable=True),
    sa.Column('email', sa.String(length=72), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('message', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
