"""empty message

Revision ID: 82a72151075c
Revises: 5f7ddf86b9fb
Create Date: 2022-04-10 15:31:23.156967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a72151075c'
down_revision = '5f7ddf86b9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('brief_bio', sa.Text(), nullable=True))
    op.add_column('about', sa.Column('professional_bio', sa.Text(), nullable=True))
    op.add_column('about', sa.Column('personal_bio', sa.Text(), nullable=True))
    op.drop_column('about', 'information')
    op.drop_column('about', 'describe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('describe', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('about', sa.Column('information', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('about', 'personal_bio')
    op.drop_column('about', 'professional_bio')
    op.drop_column('about', 'brief_bio')
    # ### end Alembic commands ###
