"""empty message

Revision ID: a24ad5827f02
Revises: f03d33e36c4e
Create Date: 2022-04-06 16:01:44.455177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24ad5827f02'
down_revision = 'f03d33e36c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('describe', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'describe')
    # ### end Alembic commands ###
