"""empty message

Revision ID: a3eb3992c2e7
Revises: bda8ebd717c8
Create Date: 2022-04-09 18:04:50.768707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3eb3992c2e7'
down_revision = 'bda8ebd717c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('note', sa.String(length=152), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'note')
    # ### end Alembic commands ###
