"""empty message

Revision ID: bda8ebd717c8
Revises: c6b0a74ecaa9
Create Date: 2022-04-09 17:09:15.711562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda8ebd717c8'
down_revision = 'c6b0a74ecaa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('category', sa.String(length=32), nullable=True))
    op.add_column('project', sa.Column('client', sa.String(length=52), nullable=True))
    op.add_column('project', sa.Column('github_url', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('project_url', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('project_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_date')
    op.drop_column('project', 'project_url')
    op.drop_column('project', 'github_url')
    op.drop_column('project', 'client')
    op.drop_column('project', 'category')
    # ### end Alembic commands ###
