"""empty message

Revision ID: fd013875ee22
Revises: 50dd9f9fcf33
Create Date: 2022-04-07 16:10:51.659539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd013875ee22'
down_revision = '50dd9f9fcf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('describe1', sa.Text(), nullable=True),
    sa.Column('describe2', sa.Text(), nullable=True),
    sa.Column('describe3', sa.Text(), nullable=True),
    sa.Column('describe4', sa.Text(), nullable=True),
    sa.Column('describe5', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    # ### end Alembic commands ###
